name: Deploy to Fly.io
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
      
      - name: Deploy to Fly.io
        run: |
          flyctl deploy --remote-only --app tarot-bot-secret
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
